// <auto-generated />
using System;
using Foot2site_V1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foot2site_V1.Migrations
{
    [DbContext(typeof(Foot2site_V1Context))]
    [Migration("20251015201750_suppresionCredit")]
    partial class suppresionCredit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Foot2site_V1.Modele.Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Id_UTILISATEUR")
                        .HasColumnType("int");

                    b.Property<bool>("Paye")
                        .HasColumnType("bit");

                    b.Property<double>("prixTotal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("Id_UTILISATEUR");

                    b.ToTable("Commande");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Ligne_Commande", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Id_COMMANDE")
                        .HasColumnType("int");

                    b.Property<int>("Id_STOCK_PRODUIT")
                        .HasColumnType("int");

                    b.Property<double>("prixUnitaire")
                        .HasColumnType("float");

                    b.Property<int>("quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Id_COMMANDE");

                    b.HasIndex("Id_STOCK_PRODUIT");

                    b.ToTable("Ligne_Commande");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description_produit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_produit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prix_unitaire_produit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Produit");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Role", b =>
                {
                    b.Property<int>("Id_Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Role"));

                    b.Property<string>("NomRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Role");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id_Role = 1,
                            NomRole = "ADMIN"
                        },
                        new
                        {
                            Id_Role = 2,
                            NomRole = "CLINET"
                        });
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Stock_produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("id_PRODUIT")
                        .HasColumnType("int");

                    b.Property<int>("id_TAILLE")
                        .HasColumnType("int");

                    b.Property<int>("quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_PRODUIT");

                    b.HasIndex("id_TAILLE");

                    b.ToTable("Stock_produit");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Taille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("taille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Taille");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            taille = "XS"
                        },
                        new
                        {
                            Id = 2,
                            taille = "S"
                        },
                        new
                        {
                            Id = 3,
                            taille = "M"
                        });
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Transaction", b =>
                {
                    b.Property<int>("Id_Transaction")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Transaction"));

                    b.Property<string>("Description_transaction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_TYPE_OPERATION")
                        .HasColumnType("int");

                    b.Property<int>("Id_User")
                        .HasColumnType("int");

                    b.Property<decimal>("Montant_operation")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id_Transaction");

                    b.HasIndex("Id_TYPE_OPERATION");

                    b.HasIndex("Id_User");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Type_Operation", b =>
                {
                    b.Property<int>("Id_Type_Operation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_Type_Operation"));

                    b.Property<string>("Nom_Type_Operation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Type_Operation");

                    b.ToTable("Type_Operation");

                    b.HasData(
                        new
                        {
                            Id_Type_Operation = 1,
                            Nom_Type_Operation = "RECHARGE"
                        },
                        new
                        {
                            Id_Type_Operation = 2,
                            Nom_Type_Operation = "DEBIT"
                        });
                });

            modelBuilder.Entity("Foot2site_V1.Modele.User", b =>
                {
                    b.Property<int>("Id_User")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id_User"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id_Role")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_User");

                    b.HasIndex("Id_Role");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Commande", b =>
                {
                    b.HasOne("Foot2site_V1.Modele.User", "utilisateur")
                        .WithMany("commandes")
                        .HasForeignKey("Id_UTILISATEUR")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("utilisateur");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Ligne_Commande", b =>
                {
                    b.HasOne("Foot2site_V1.Modele.Commande", "commande")
                        .WithMany("lignes_Commande")
                        .HasForeignKey("Id_COMMANDE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foot2site_V1.Modele.Stock_produit", "stock_Produit")
                        .WithMany("lignesCommande")
                        .HasForeignKey("Id_STOCK_PRODUIT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("commande");

                    b.Navigation("stock_Produit");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Stock_produit", b =>
                {
                    b.HasOne("Foot2site_V1.Modele.Produit", "produit")
                        .WithMany("stocks")
                        .HasForeignKey("id_PRODUIT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foot2site_V1.Modele.Taille", "taille")
                        .WithMany("Stock_Produits_List")
                        .HasForeignKey("id_TAILLE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("produit");

                    b.Navigation("taille");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Transaction", b =>
                {
                    b.HasOne("Foot2site_V1.Modele.Type_Operation", "TypeOperation")
                        .WithMany("Transactions")
                        .HasForeignKey("Id_TYPE_OPERATION")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foot2site_V1.Modele.User", "Utilisateur")
                        .WithMany("Transactions")
                        .HasForeignKey("Id_User")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeOperation");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.User", b =>
                {
                    b.HasOne("Foot2site_V1.Modele.Role", "Role")
                        .WithMany("User")
                        .HasForeignKey("Id_Role")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Commande", b =>
                {
                    b.Navigation("lignes_Commande");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Produit", b =>
                {
                    b.Navigation("stocks");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Role", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Stock_produit", b =>
                {
                    b.Navigation("lignesCommande");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Taille", b =>
                {
                    b.Navigation("Stock_Produits_List");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Type_Operation", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.User", b =>
                {
                    b.Navigation("Transactions");

                    b.Navigation("commandes");
                });
#pragma warning restore 612, 618
        }
    }
}
