// <auto-generated />
using Foot2site_V1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Foot2site_V1.Migrations
{
    [DbContext(typeof(Foot2site_V1Context))]
    [Migration("20251013151813_modifi")]
    partial class modifi
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Foot2site_V1.Modele.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("description_produit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nom_produit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prix_unitaire_produit")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Produit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            description_produit = "le maillot du barcelone à domicile de 2017",
                            nom_produit = "Maillot Barcelone 2017",
                            prix_unitaire_produit = 65.0
                        },
                        new
                        {
                            Id = 2,
                            description_produit = "le maillot du Real Madrid à l'extérieur de 2014",
                            nom_produit = "Maillot Real Madrid 2014",
                            prix_unitaire_produit = 80.0
                        });
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Stock_produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("id_PRODUIT")
                        .HasColumnType("int");

                    b.Property<int>("id_TAILLE")
                        .HasColumnType("int");

                    b.Property<int>("quantite")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("id_PRODUIT");

                    b.HasIndex("id_TAILLE");

                    b.ToTable("Stock_produit");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            id_PRODUIT = 1,
                            id_TAILLE = 2,
                            quantite = 10
                        },
                        new
                        {
                            Id = 2,
                            id_PRODUIT = 1,
                            id_TAILLE = 1,
                            quantite = 20
                        },
                        new
                        {
                            Id = 3,
                            id_PRODUIT = 2,
                            id_TAILLE = 4,
                            quantite = 20
                        });
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Taille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("taille")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Taille");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            taille = "XS"
                        },
                        new
                        {
                            Id = 2,
                            taille = "S"
                        },
                        new
                        {
                            Id = 3,
                            taille = "M"
                        },
                        new
                        {
                            Id = 4,
                            taille = "L"
                        },
                        new
                        {
                            Id = 5,
                            taille = "XL"
                        },
                        new
                        {
                            Id = 6,
                            taille = "XLL"
                        });
                });

            modelBuilder.Entity("Foot2site_V1.Modele.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Credit")
                        .HasColumnType("float");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Stock_produit", b =>
                {
                    b.HasOne("Foot2site_V1.Modele.Produit", "produit")
                        .WithMany("stocks")
                        .HasForeignKey("id_PRODUIT")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Foot2site_V1.Modele.Taille", "taille")
                        .WithMany("Stock_Produits_List")
                        .HasForeignKey("id_TAILLE")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("produit");

                    b.Navigation("taille");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Produit", b =>
                {
                    b.Navigation("stocks");
                });

            modelBuilder.Entity("Foot2site_V1.Modele.Taille", b =>
                {
                    b.Navigation("Stock_Produits_List");
                });
#pragma warning restore 612, 618
        }
    }
}
